/**
 * The passage corpus that `search_docs` / `fetch_docs` read, and that
 * `llms.txt` renders. One source, so an agent and a human cannot be told
 * different things about how SENTINEL works.
 *
 * Keep these in sync with the copy on the landing and docs pages.
 */
export type Passage = {
  readonly id: string;
  readonly title: string;
  readonly kind: "landing" | "docs" | "agent";
  readonly text: string;
};

export const PASSAGES: readonly Passage[] = [
  {
    id: "landing:problem",
    title: "The problem SENTINEL solves",
    kind: "landing",
    text: "A dependency advisory lands. Someone has to work out whether this repository is genuinely affected, whether the fix is a one-line bump or a breaking change, whether the test suite survives it, and then write the pull request. That is an afternoon per advisory, and most teams do it late — or not at all. Every software team has this backlog. The work is repetition at scale, and repetition is what an agent should be doing.",
  },
  {
    id: "landing:pipeline",
    title: "The eight stages",
    kind: "landing",
    text: "01 Inventory — read package.json and the lockfile, resolving real installed versions rather than declared ranges. 02 Triage — query the GitHub Advisory Database with OSV fallback, keeping only advisories whose version range actually matches. 03 Delegate — one subagent per affected package, each with a clean context window. 04 Assess — classify each upgrade as patch, minor or major and measure how widely the package is imported. 05 Plan — one safe target version per package, the highest fix version, so no advisory is left open. 06 Patch — generate the updated package.json, preserving the project's range operators. 07 Verify — install and run the test suite in an isolated Daytona sandbox. 08 Propose — open the pull request, then pause and wait for a human.",
  },
  {
    id: "landing:tools",
    title: "The seven MCP tools",
    kind: "landing",
    text: "scan_dependencies, lookup_advisories, assess_blast_radius and summarise_triage are annotated readOnlyHint and need no approval. propose_patch is read-only too — it writes only inside the sandbox. open_pull_request and merge_pull_request are annotated destructiveHint, so the harness raises a real approval gate. The classification lives next to the implementation and both front ends inherit it; a mis-tagged tool fails closed.",
  },
  {
    id: "landing:approval",
    title: "The approval gate",
    kind: "landing",
    text: "The turn ends at open_pull_request. The console shows the full tool call and its arguments, and nothing happens until a person clicks. Denial is the default everywhere: empty input, EOF, Escape and unparseable answers all deny. The web API only accepts approvals for tool calls the harness actually raised, so a model cannot approve itself.",
  },
  {
    id: "landing:kill-switch",
    title: "The kill switch",
    kind: "landing",
    text: "Set SENTINEL_ALLOW_REMOTE_WRITES=false and the destructive tools refuse before any network call, regardless of what the model or the approval UI claims. GitHubClient re-checks the switch at the point of mutation, and branch names are generated by SENTINEL — the model never supplies a ref.",
  },
  {
    id: "landing:degradation",
    title: "Degradation strategy",
    kind: "landing",
    text: "Missing model key: hard fail at provision, naming the exact environment variable. Missing DAYTONA_API_KEY: the sandbox is disabled and patches are reported UNVERIFIED rather than silently claimed. Missing GITHUB_TOKEN: GitHub tools return a typed not-configured error while scanning and triage keep working. Harness not running: clients print the npx @truefoundry/trueforge command instead of a stack trace.",
  },
  {
    id: "landing:secrets",
    title: "Keeping secrets out",
    kind: "landing",
    text: "Server keys live in .env, git-ignored, read in one place. Browser keys live in localStorage, are masked in the UI and are sent per request only to this app's own API routes over HTTPS; nothing is persisted server-side. Two-layer redaction — exact registered values plus ten credential shapes — scrubs every log line, tool result and SSE frame.",
  },
  {
    id: "docs:quickstart",
    title: "Run it locally",
    kind: "docs",
    text: "npm install, then npm run dev for http://localhost:3000. The Scan station needs no key: it triages a real manifest against the GitHub Advisory Database with OSV as fallback. Deploying to Vercel is a repository import; optional environment variables are SENTINEL_ALLOW_REMOTE_WRITES, GITHUB_TOKEN, DAYTONA_API_KEY and TRUEFORGE_URL.",
  },
  {
    id: "agent:bridge",
    title: "The agent bridge: WebMCP and remote MCP",
    kind: "agent",
    text: "This site is a tool server for AI agents in two shapes. In the browser it registers every tool on document.modelContext, the W3C WebMCP surface (the deprecated navigator.modelContext alias resolves to the same context), with title, inputSchema and safety annotations, and registration is abortable through an AbortController. Outside the browser the identical contract is served over remote MCP at /api/mcp using stateless Streamable HTTP: server/discover, tools/list and tools/call, with per-request _meta protocol version, Mcp-Method and Mcp-Name routing headers, and ttlMs plus cacheScope on list results. Legacy clients that send an initialize handshake are supported at protocol versions 2025-11-25, 2025-06-18 and 2025-03-26.",
  },
  {
    id: "agent:webmcp-requirements",
    title: "What a browser needs to see these tools",
    kind: "agent",
    text: "WebMCP requires a secure context (https or localhost) and a browser with the API: Chrome 149+ in the public origin trial, Chrome 146 Canary, and the ChatGPT desktop app's built-in browser and ChatGPT Sites since 25 August 2026. Firefox and Safari have no implementation yet. Where no native modelContext exists, SENTINEL installs a spec-shaped polyfill so the on-page cockpit and in-page agents keep working, and the console says plainly that the polyfill is in-page only and is not visible to an external agent.",
  },
  {
    id: "agent:connect-chatgpt",
    title: "Connect it to ChatGPT",
    kind: "agent",
    text: "Two paths. 1) The built-in browser: open this site in the ChatGPT desktop app and ask ChatGPT or Codex to use the site — the page's registered WebMCP tools are surfaced automatically, subject to the usual website-access and sensitive-action confirmations. 2) A connector: Settings, Apps and Connectors, Advanced, enable Developer mode, then create an app pointing at https://your-host/api/mcp with Streamable HTTP and No Authentication (or OAuth plus SENTINEL_MCP_TOKEN when you want a bearer token). Claude, Cursor, Claude Code, Gemini CLI, Zed and VS Code use the same URL. To verify either path without an agent, open the Bridge station in the console and run the conformance check.",
  },
  {
    id: "agent:verification",
    title: "How the bridge is checked",
    kind: "agent",
    text: "npm run check:mcp runs a conformance suite against the endpoint: discovery and version negotiation, deterministic tools/list with cache fields, a successful tools/call, invalid-argument rejection, a refusal from a destructive tool, header-mismatch rejection, unsupported protocol version, Origin validation, method-not-found, and the legacy initialize handshake. npm run check:webmcp runs the same contract through the WebMCP core in Node: schema validation, duplicate-name rejection, abort-signal unregistration, toolchange events and stringified results. The Bridge station runs a live subset from inside the browser.",
  },
  {
    id: "labs:omni",
    title: "The OMNI-LAB",
    kind: "landing",
    text: "Five in-browser laboratories register seventeen tools on the same model context: BreachLab (AST taint tracing, sandbox detonation, hotpatch synthesis), BioSynth (crambin coordinates, point mutagenesis with delta-delta-G, binding pockets), ChronoForensic (sensor streams, acoustic TDOA triangulation, sealed SHA-256 dossier), MetaLoop (agent trace trees, synthetic tool injection, drift compensation) and ZK Escrow (SHA-256 and HMAC-SHA-256 digests with milestone-gated release). The engines are dependency-free JavaScript, so the bridge can execute them server-side and a tab can execute them in-page — identical results either way.",
  },
];

/** Tiny, dependency-free BM25-ish scorer: enough for a page of prose. */
export function searchPassages(query: string, limit = 6) {
  const terms = query
    .toLowerCase()
    .split(/[^a-z0-9]+/i)
    .filter((term) => term.length > 2);
  if (terms.length === 0) return [];

  const scored = PASSAGES.map((passage) => {
    const haystack = `${passage.title} ${passage.text}`.toLowerCase();
    let score = 0;
    for (const term of terms) {
      let index = haystack.indexOf(term);
      while (index !== -1) {
        score += 1;
        index = haystack.indexOf(term, index + term.length);
      }
    }
    if (terms.some((term) => passage.title.toLowerCase().includes(term))) score += 3;
    return { passage, score };
  })
    .filter((entry) => entry.score > 0)
    .sort((a, b) => b.score - a.score || a.passage.id.localeCompare(b.passage.id))
    .slice(0, Math.max(1, Math.min(limit, 20)));

  return scored.map(({ passage, score }) => ({
    id: passage.id,
    title: passage.title,
    kind: passage.kind,
    score,
    excerpt:
      passage.text.length > 320 ? `${passage.text.slice(0, 317).trimEnd()}…` : passage.text,
  }));
}

/** The llms.txt / agent card rendering, built from the same passages. */
export function renderAgentDigest(endpoint: string, tools: { name: string; description: string }[]): string {
  const lines: string[] = [
    "# SENTINEL — agent digest",
    "",
    "> Autonomous supply-chain CVE strike team on the TrueForge agent harness. Reads your",
    "> dependency tree, triages advisories against the versions you actually ship, prepares",
    "> the patch, and stops for a human before the pull request.",
    "",
    "## Machine interfaces",
    "",
    `- Remote MCP (Streamable HTTP, stateless 2026-07-28 + legacy handshake): \`${endpoint}\``,
    "- WebMCP (in-page tools): `document.modelContext` — 17 OMNI-LAB tools plus the domain tools",
    "- Console: `/app` · Docs: `/docs` · Capability report: `GET /api/status`",
    "",
    "## How to behave against this API",
    "",
    "```",
    AGENT_INSTRUCTIONS_LINES.join("\n"),
    "```",
    "",
    "## Tools",
    "",
    ...tools.map((tool) => `- \`${tool.name}\` — ${tool.description}`),
    "",
    "## Reference",
    "",
    ...PASSAGES.map((passage) => `### ${passage.title}\n\n${passage.text}\n`),
  ];
  return lines.join("\n");
}

const AGENT_INSTRUCTIONS_LINES = [
  "Prefer get_project_status once, then work the stages in order:",
  "  scan_dependencies -> lookup_advisories -> assess_blast_radius",
  "  -> summarise_triage -> propose_patch.",
  "Send the *installed* version to lookup_advisories, not the declared range.",
  "open_pull_request and merge_pull_request are destructive and refuse unless",
  "SENTINEL_ALLOW_REMOTE_WRITES=true is set server-side and the exact",
  "confirmation string is passed in 'confirm'. Never invent a confirmation.",
  "Report a patch as UNVERIFIED unless a Daytona sandbox ran the tests.",
  "Never print or store API keys; this server never returns one.",
];
